_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 0

min_epochs: 1
max_epochs: 10
max_steps: ${train.total_steps}
weights_summary: null
progress_bar_refresh_rate: 1
resume_from_checkpoint: null
log_every_n_steps: 50
val_check_interval: 5
limit_val_batches: 2
limit_test_batches: 2