_target_: src.models.model.get_model

teacher: None
pretrained_model_name_or_path: "distilbert-base-multilingual-cased"
use_pretrained_weights: true

cfg:
  output_hidden_states: true
  output_attentions: true