_target_: src.loss.loss.GeneralLoss
defaults:
  - base_loss@base_loss.hidden_mse: hidden_mse.yaml
  - base_loss@base_loss.att_mse: att_mse.yaml

base_loss:
  att_mse:
    mapping: {6: 12}
  hidden_mse:
    mapping: {6: 12}

loss_weighting:
  hidden_mse: 0.5
  att_mse: 0.5
