# @package _global_

defaults:
  - base_loss@students.individual.loss.base_loss.mlm: mlm.yaml
  - base_loss@students.individual.loss.base_loss.softtargets_kl: softtargets_kl.yaml

students:
  individual:
    loss:
      _target_: src.loss.loss.GeneralLoss

      base_loss:
        softtargets_kl:
          temperature: 4.0

      loss_weighting:
        mlm: 0.5
        softtargets_kl: 0.5

    model:
      cfg:
        output_attentions: false

