_target_: src.loss.loss.GeneralLoss
defaults:
  - base_loss@base_loss.mlm: mlm.yaml
  - base_loss@base_loss.softtargets_kl: softtargets_kl.yaml
  - base_loss@base_loss.hidden_mse: hidden_mse.yaml
  - base_loss@base_loss.att_mse: att_mse.yaml

base_loss:
  softtargets_kl:
    temperature: 4.0
  hidden_mse:
    mapping: {1: 1, 2: 3, 3: 5, 4: 7, 5: 9, 6: 12}
  att_mse:
    mapping: {1: 1, 2: 3, 3: 5, 4: 7, 5: 9, 6: 12}

loss_weighting:
  mlm: 0.0005
  softtargets_kl: 0.0005
  hidden_mse: 0.499
  att_mse: 0.499
