_target_: src.loss.loss.GeneralLoss
defaults:
  - base_loss@base_loss.softtargets_kl: softtargets_kl.yaml
  - base_loss@base_loss.hidden_mse: hidden_mse.yaml
  - base_loss@base_loss.att_mse: att_mse.yaml

base_loss:
  softtargets_kl:
    temperature: 4.0
  hidden_mse:
    mapping: {4: 12}
  att_mse:
    mapping: {4: 12}

loss_weighting:
  softtargets_kl: 0.01
  hidden_mse: 0.495
  att_mse: 0.495

