_target_: src.loss.loss.GeneralLoss
defaults:
  - base_loss@base_loss.hidden_mse: hidden_mse.yaml

base_loss:
  hidden_mse:
    mapping: {1: 1, 2: 3, 3: 5, 4: 7, 5: 9, 6: 12}

loss_weighting:
  hidden_mse: 1.0
