defaults:
  - ../tokenizer@tokenizer: autotokenizer.yaml

model:
  _target_: src.models.model.get_automodel

  pretrained_model_name_or_path: "prajjwal1/bert-tiny"
  use_pretrained_weights: true

  output_hidden_states: true
  output_attentions: true

# Define Tokenizer for teacher/student
tokenizer:
  pretrained_model_name_or_path: ${..model.pretrained_model_name_or_path}
