# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "tensorboard/"
  name: "default"
  version: null
  log_graph: True
  default_hp_metric: false
  prefix: ""
