_target_: src.models.architecture.tiny_model.get_tiny_model

defaults:
  - automodel.yaml

teacher: None

cfg:
  hidden_size: 768 # must be dividable by no. of heads!
  num_hidden_layers: 2

weights_from_teacher:
  embeddings: False
  transformer_blocks: False

mapping: {0: 0, 1: 1} # TODO: Allowing for using other losses?