_target_: src.models.model.get_tiny_model

defaults:
  - automodel.yaml

teacher: None

cfg:
  hidden_size: 768 # must be dividable by no. of heads!
  num_hidden_layers: 4

weights_from_teacher:
  embeddings: True
  transformer_blocks: True

mapping: {0: 0, 1: 2, 2: 4, 3: 6} # TODO: Allowing for using other losses?