_target_: src.models.model.get_tiny_model

defaults:
  - automodel.yaml

teacher: None

cfg:
  hidden_size: 288 # must be dividable by no. of heads!
  num_hidden_layers: 2

weights_from_teacher:
  embeddings: True
  transformer_blocks: False

mapping: { 1: 2, 2: 4} # TODO: Allowing for using other losses?