_target_: src.models.model.get_tiny_model

defaults:
  - automodel.yaml

teacher: None

cfg:
  hidden_size: 768 # must be dividable by no. of heads!
  num_hidden_layers: 4

weights_from_teacher:
  embeddings: False
  transformer_blocks: False

mapping: {0: 0, 1: 3, 2: 7, 3: 11} # TODO: Allowing for using other losses?