_recursive_: false
_target_: src.distillation.adversarial_learning.AdversarialLearning

validate_before_training: True

generator:
  optimizer:
    _target_: transformers.optimization.Adafactor
    weight_decay: 0.01

discriminator:
  optimizer:
    _target_: transformers.optimization.Adafactor
    weight_decay: 0.01