# @package _global_
distillation_type: monolingual

distillation:
  _recursive_: false
  _target_: src.distillation.monolingual.Monolingual

  # Weight sharing
  # n_layers: int or list of ints
  # input (embedding layer)


