_target_: src.datamodules.mnli.MNLIDataModule

model_name_or_path: ${model.model_name_or_path}
data_dir: ${data_dir}/multinli_1.0
batch_size: 64
num_labels: 3
num_workers: 4
pin_memory: true
samples_per_cls: 0
sample_with_replace: False
sample_seed: ${seed}
max_length: 512
