# By default we turn off recursive instantiation, allowing the user to instantiate themselves at the appropriate times.
_recursive_: false

_target_: transformers.AutoTokenizer.from_pretrained
pretrained_model_name_or_path: ${..model.pretrained_model_name_or_path}
use_fast: true

