# By default we turn off recursive instantiation, allowing the user to instantiate themselves at the appropriate times.
_recursive_: false

run_test_after_fit: True
total_steps: 20
lr: 0.0002
output_dir: '.'

# read in dataset
batch_size: 2
num_workers: 0

metric:
  _target_: datasets.load_metric
  path: "accuracy"